# Generated by Django 2.1.2 on 2019-03-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('introduce', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('addtime', models.DateField(auto_now_add=True)),
                ('updatatime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Classify'),
        ),
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.ManyToManyField(to='myblog.Label'),
        ),
    ]
