# Generated by Django 2.2 on 2019-04-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_pinglun'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='liulangliang',
            field=models.IntegerField(default=0),
        ),
    ]
